package io.github.johnjeffords.talkingclock.ui.settings

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.PlayCircle
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.RadioButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import io.github.johnjeffords.talkingclock.R
import io.github.johnjeffords.talkingclock.domain.speech.Phrasebook
import io.github.johnjeffords.talkingclock.domain.speech.SpeakingStyle
import java.time.LocalTime

/**
 * The speaking-style picker (design frame 20): a radio list showing each
 * style's phrasing of 10:24, with a play button that speaks a live preview
 * in that style. Picking a style applies immediately, app-wide.
 */
@Composable
fun SpeakingStyleScreen(
    selected: SpeakingStyle,
    onSelect: (SpeakingStyle) -> Unit,
    onPreview: (SpeakingStyle) -> Unit,
    modifier: Modifier = Modifier,
) {
    Column(modifier = modifier.fillMaxSize()) {
        Text(
            text = stringResource(R.string.style_screen_hint),
            style = MaterialTheme.typography.bodyLarge,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            modifier = Modifier.padding(horizontal = 22.dp, vertical = 16.dp),
        )
        SpeakingStyle.entries.forEach { style ->
            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier
                    .fillMaxWidth()
                    .clickable { onSelect(style) }
                    .padding(start = 12.dp, end = 12.dp, top = 6.dp, bottom = 6.dp),
            ) {
                RadioButton(selected = style == selected, onClick = { onSelect(style) })
                Spacer(Modifier.width(6.dp))
                Column(Modifier.weight(1f)) {
                    Text(style.label(), style = MaterialTheme.typography.bodyLarge)
                    // The exact sentence this style produces for 10:24 —
                    // generated by the real Phrasebook, so the preview text
                    // can never drift from what the app actually says.
                    Text(
                        text = "“${Phrasebook.timeAnnouncement(PREVIEW_TIME, style)}”",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
                IconButton(onClick = { onPreview(style) }) {
                    Icon(
                        imageVector = Icons.Outlined.PlayCircle,
                        contentDescription = stringResource(R.string.style_play_preview),
                        tint = MaterialTheme.colorScheme.primary,
                    )
                }
            }
        }
    }
}

/** The design's canonical preview time. */
private val PREVIEW_TIME: LocalTime = LocalTime.of(10, 24)
